### ISSUE TITLE
Add ExaSPIM subject procedure tracking sheet endpoint

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-service#90]
Procedure metadata for ExaSPIM brains is being tracked in an Excel workbook and will be for the foreseeable future.  Let's add a mapping service endpoint to extract out viral injections / other procedures.

Subject procedure tracking sheet:
`https://alleninstitute.sharepoint.com/:x:/s/NeuralDynamics/EeZRHQRyy9xIjXyRfIZHyjcBkInCouRWPK1ZP8XmvLJA1w?e=nOgGFi`

Acceptance Criteria:

- [ ] Meet with Daphne and David/Saskia to get an overview of the sheet.
- [ ] Add an endpoint to the metadata service that can extract subject procedures from this sheet.
- [ ] When a `/procedures` call comes in, check this sheet (in addition to the two Sharepoint databases).
- [ ] Output conforms to the latest `Procedures` schema.

**Comment by jtyoung84** [comment]
Blocked. Service account needs read-only permissions to access this file.

**Comment by jtyoung84** [comment]
Putting this back on the backlog until we find out whether or not this information can be retrieved from a different database. The current progress is tracked on the branch: https://github.com/AllenNeuralDynamics/aind-metadata-service/tree/feat-90-extra-exaspim/src/aind_metadata_service

**Comment by jtyoung84** [comment]
Blocked again. Exploring LAS to see if this info is in there.

**Comment by jtyoung84** [comment]
Not gonna do it
